### ISSUE TITLE
Making Whole Page Fullscreen turns background black

### ISSUE THREAD

**Issue by jowilhnson** [flowkey/bigscreen#1]
I'm calling BigScreen.toggle(); from the event listener on a button, as per the documentation. And while it is working, it is turning large portions of the background black. So far, no attempt at countering it with CSS styling is working. I've tried applying a white background to the HTML element and the body element and nothing changes. 

What element is made fullscreen when BigScreen.toggle() is used to take the entire page fullscreen?

**Comment by nerdmed** [comment]
@soitech as i can see the bigscreen library will take the full page to fullscreen if you do not pass an element. You could try passing an element to the function call. It could also be a browser thing. On which browser are you using it?

**Comment by nerdmed** [comment]
@soitech  please have a look at this: http://www.sitepoint.com/use-html5-full-screen-api/
seems that the fullscreen API has its own pseudo call in the browsers, that is also prefixed in some of them:

CSS:

``` css
:fullscreen {
    ...
}
----
:-webkit-full-screen {
}

:-moz-full-screen {
}

:-ms-fullscreen {
}

:fullscreen {
}
```

**Comment by jowilhnson** [comment]
I've currently only tested it on Chrome 47 on OSX. 
I did some searching before coming here and tried various CSS such as 

```
*:fullscreen, *:-webkit-full-screen, *:-moz-full-screen {
    background: rgba(255,255,255,0);
}
```

with no luck. I will check the link you posted, and if all else fails try passing an element and styling that specific element if necessary. Will report back if I have any success. Thanks.

**Comment by nerdmed** [comment]
alright. If you could share a minimal meteor app it would be very useful to support if this is an issue of the package

**Comment by jowilhnson** [comment]
I'm pretty sure at this point that it is not an issue of the package, but of the somewhat fractured nature of the fullscreen API at this point. 

Referencing the article you linked: 

> The backdrop is a pseudo element behind the fullscreen element but above all other page content. It is supported in IE11, but not Firefox and Opera 12. Chrome, Safari, and Opera 15+ include the backdrop element but do not permit it to be styled. 

And: 

> Opera 12 is similar to IE11 but shows a transparent backdrop. Firefox ignores the dimensions. In Chrome, Safari, and Opera 15+ the element is centered with a black backdrop.

So basically every browser handles the backdrop somewhat differently, if at all. 
In Firefox, BigScreen.toggle() appears as I'd expect, with the usual white background. 

Reading through this: https://developers.google.com/web/updates/2011/10/Let-Your-Content-Do-the-Talking-Fullscreen-API?hl=en gives a little bit of insight into how some styling for fullscreen can be handled in Chrome. Basically I'm thinking that since the backdrop is black in chrome and can't be styled, I will have to tinker with styles to ensure that the elements on the screen fully cover the backdrop. Knowing this I've noticed in fullscreen my body element is only filling a small portion of the screen, at the center, so I should probably be passing the body element to fullscreen, and making sure it sets width/height 100% for the element in fullscreen. 

Thanks for your time.
